/**
 * Persistent vm context.
 *
 * The context is created lazily on first use and regenerated by `reset()`. Each host
 * function name present at creation time gets a call port in the context. The port looks
 * up the function bound to the currently running cell through `resolveHostFn` (backed by
 * `cell.ts`'s AsyncLocalStorage), so the context can be long-lived while cells come and go.
 */

import vm from "node:vm";
import type { HostFnCallable, HostFnRegistry } from "./registry.ts";

/** Host globals exposed to cells. Everything else (process, Bun, require, console) is absent. */
export const ALLOWED_GLOBALS = [
	"setTimeout",
	"clearTimeout",
	"fetch",
	"URL",
	"TextEncoder",
	"TextDecoder",
	"structuredClone",
] as const;

export interface ReplContextOptions {
	registry: HostFnRegistry;
	/** Resolve the callable bound to the current cell, or undefined outside a cell. */
	resolveHostFn(name: string): HostFnCallable | undefined;
}

export class ReplContext {
	readonly #registry: HostFnRegistry;
	readonly #resolveHostFn: (name: string) => HostFnCallable | undefined;
	#context: vm.Context | undefined;

	constructor(options: ReplContextOptions) {
		this.#registry = options.registry;
		this.#resolveHostFn = options.resolveHostFn;
	}

	get context(): vm.Context {
		if (this.#context === undefined) {
			this.#context = this.#createContext();
		}
		return this.#context;
	}

	get created(): boolean {
		return this.#context !== undefined;
	}

	reset(): void {
		this.#context = undefined;
	}

	#createContext(): vm.Context {
		const sandbox: Record<string, unknown> = {};
		const host = globalThis as unknown as Record<string, unknown>;
		for (const name of ALLOWED_GLOBALS) {
			sandbox[name] = host[name];
		}
		for (const entry of this.#registry.list()) {
			const name = entry.name;
			sandbox[name] = (...args: unknown[]): unknown => {
				const fn = this.#resolveHostFn(name);
				if (fn === undefined) {
					throw new ReferenceError(`${name} is not available outside a cell`);
				}
				return fn(...args);
			};
		}
		const context = vm.createContext(sandbox);
		// Bun installs a default console into new contexts; spirits intentionally omits it.
		vm.runInContext("delete globalThis.console", context);
		return context;
	}
}
